### ISSUE TITLE
Mixed content error on index.html

### ISSUE THREAD

**Issue by moustachu** [will94290/my_syte#1]
Hello !! 

C'est le début de ton aventure donc c'est normal qu'il y ai des erreurs 😛 
Et puis même si je pourrais te faire les remarques en direct on va s'amuser un peu avec le processus standard de correction.

**Branche `gh-pages`**

Donc là on parle juste de du problème de "mixed content" entre HTTP et HTTPS.
Github te fourni une URL sécurisée en HTTPS mais si tu mets des liens vers du contenu en HTTP, les navigateurs récents ne vont pas être content et parfois bloqué le contenu.

Ici on parle des liens contenu dans `style.css`
et plus particulièrement de la ligne 1
```css
@import url("http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Montserrat:400,700");
```
**--> à mettre à jour en HTTPS**

De plus je remarque que les polices chargées ne sont pas utilisées dans ta page. 
D'intuition, je dirais que tu voulais faire 
```css
body {
...
  font-family: "Open Sans";
}
h1 {
...
  font-family: "Montserrat";
}
```
ou alors en utilisant les classes CSS déjà présentes

```css
.titre {
...
  font-family: "Open Sans";
}
.texte {
...
  font-family: "Montserrat";
}
```
